export { default as Navbar } from './Navbar/Navbar.js'
export { default as Footer } from './Footer/Footer.js'
export { default as InfoSection } from './InfoSection/InfoSection.js'
export { default as ImageSliderr } from './ImageSlider/ImageSlider2.js'
export { default as ProductSection } from './ProductSection/ProductSection.js'
export { default as AdminDashboard } from './AdminDashboard/AdminDashboard.js'